### ISSUE TITLE
`build.rs` regenerates icons unnecessarily on every build

### ISSUE THREAD

**Issue by aqrln** [SorenHolstHansen/phosphor-leptos#3]
### Problem

The build script regenerates all the icons every time the crate is compiled. The generated icons are already included in the published crate and committed in the repo, so this is not necessary and only increases compile time. It is also problematic when building with Nix:

```
error: failed to run custom build command for `phosphor-leptos v0.1.0`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/phosphor-leptos-5856d3cc071d4b6d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /nix/store/n50qmb06q61b68nah8zwvzvlpdx5ppbp-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/phosphor-leptos-0.1.0/build.rs:65:33:
  called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Finally, it also significantly increases the size of the published cargo crate, as it requires the `core` directory to be published as part of the package to make it possible to generate the icons (even though it's not used in any way at run time and contains nothing required to compile included Rust source files), which takes 59 out of 66 MB unpacked package size.

### Suggested solution

* Remove `build.rs` and make its contents a standalone script that is manually run when updating the icons, commit the result and run nothing special on build.
* Exclude the `core` directory from the published package.

**Comment by SorenHolstHansen** [comment]
Sounds like a great idea! I don't have the time right now, but will perhaps look into it in the future

**Comment by aqrln** [comment]
No worries if you don't have time, I'll open a PR then!
