### ISSUE TITLE
Add features to only build used icons.

### ISSUE THREAD

**Issue by SleeplessOne1917** [SorenHolstHansen/phosphor-leptos#7]
Some of the other icon libraries I've experimented with, [leptos-icons](https://github.com/Carlosted/leptos-icons) and [leptos_heroicons](https://crates.io/crates/leptos_heroicons) gate icons behind features so unused icons don't have to be compiled. A project of mine took noticeably longer to build after adding this crate as a dependency, and I believe this feature approach could help remedy that.

**Comment by SorenHolstHansen** [comment]
Yeah, I agree that this would be nice, but there are currently 1000+ icons in Phosphor, and per https://blog.rust-lang.org/2023/10/26/broken-badges-and-23k-keywords.html the crates team have limited all new crates to have at most 300 features

**Comment by SleeplessOne1917** [comment]
Perhaps related icons can be grouped into the same feature? So features would be categories of icons instead of individual icons. As it is now, when I try to build my project in debug mode, this dependency adds a significant amount of time and chokes my laptop.

**Edit**: My build time is not affected on my much stronger desktop.

**Comment by SorenHolstHansen** [comment]
Yeah, could be an idea. But it is a lot of features to maintain by hand, and can quickly become unwieldy

**Comment by ghost** [comment]
Hi there, I added a pull request #10 that should do this.
It uses the categories exported in the TS file to add feature flags to the generated icon .rs files as well as updates the cargo.toml to add the needed features.

Let me know if this helps any.
PS the cargo.toml features are: (So not too many, but helps speed it up quite a bit i thought)

```[features]
default = ["all"]
all = [
	"arrows",
	"brand",
	"commerce",
	"communication",
	"design",
	"development",
	"editor",
	"finance",
	"games",
	"health",
	"map",
	"media",
	"nature",
	"objects",
	"office",
	"people",
	"system",
	"uncategorized",
	"weather"
]
arrows = []
brand = []
commerce = []
communication = []
design = []
development = []
editor = []
finance = []
games = []
health = []
map = []
media = []
nature = []
objects = []
office = []
people = []
system = []
uncategorized = []
weather = []
`

**Comment by SorenHolstHansen** [comment]
Cool, I will close this issue for now due to #10
